version: "3.7"
services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql:authentication
      - DB_USER=postgres
      - DB_PASSWORD=password
      - PORT=8080
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=authentication
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
    volumes:
      - db_data:/var/lib/postgresql/data
  db_migrate:
    build:
      context: ./docker/migrate
      dockerfile: ./Dockerfile-migrate.dev
    depends_on:
      - db
    # docker composeで起動時は開発用途なので migrate up で良い、運用時は command の arguments を調整することで down や up 1 などで何を適用するか決定する
    command: ["-database", "postgres://postgres:password@db:5432/authentication?sslmode=disable", "-path", "/migrations/", "up"]
    profiles: ["migration"]

volumes:
  db_data:

