version: "3.7"
services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://db:5432/authentication
      - DB_USER=postgres
      - DB_PASSWORD=password
    depends_on:
      - db
  test_web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    volumes:
      - .:/app
    environment:
      - DB_URL=jdbc:postgresql://db:5432/test_authentication
      - DB_USER=postgres
      - DB_PASSWORD=password
    depends_on:
      - db
    profiles: ["test"]
  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/sql:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=authentication
  db_migrate:
    build:
      context: ./docker/migrate
      dockerfile: ./Dockerfile-migrate.dev
    depends_on:
      - db
    # docker composeで起動時は開発用途なので migrate up で良い、運用時は command の arguments を調整することで down や up 1 などで何を適用するか決定する
    profiles: ["tool"]
    tty: true
    volumes:
      - ./docker/migrate/version:/migrations
