version: "3.7"
services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.dev
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql:authentication
      - DB_USER=postgres
      - DB_PASSWORD=password
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/sql:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=authentication