# ベースイメージ
FROM migrate/migrate:v4.16.2

# migration に使う file をコンテナ内の migrations ファイルへ保持する
ARG DATABASE_URL
ENV DATABASE_URL=${DATABASE_URL}

ADD entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["./entrypoint.sh"]
