name: Run sbt test
# TODO ブランチ戦略次第でトリガーとなるブランチを変更する

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - 'src/**'
  push:
    branches:
      - main
    paths:
      - 'src/**'

env:
  POSTGRES_CACHE_PATH: postgres-image
  POSTGRES_VERSION: 15-alpine
  MIGRATE_CACHE_PATH: migrate-image
  MIGRATE_VERSION: v4.16.2

jobs:
  deploy:
    name: Run sbt test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache a Postgres Docker image
        id: cache-postgres
        uses: actions/cache@v3
        with:
          path: ${{ env.POSTGRES_CACHE_PATH }}
          key: ${{ runner.os }}-postgres-${{ env.POSTGRES_VERSION }}

      - name: Pull and save a Postgres Docker image
        if: steps.cache-postgres.outputs.cache-hit != 'true'
        run: |
          docker pull postgres:${{ env.POSTGRES_VERSION }} 
          docker save postgres:${{ env.POSTGRES_VERSION }} -o ${{ env.POSTGRES_CACHE_PATH }}

      - name: Cache a migrate Docker image
        id: cache-migrate
        uses: actions/cache@v3
        with:
          path: ${{ env.MIGRATE_CACHE_PATH }}
          key: ${{ runner.os }}-migrate-${{ env.MIGRATE_VERSION }}

      - name: Pull and save a migrate Docker image
        if: steps.cache-migrate.outputs.cache-hit != 'true'
        run: |
          docker pull migrate/migrate:${{ env.MIGRATE_VERSION }} 
          docker save migrate/migrate:${{ env.MIGRATE_VERSION }} -o ${{ env.MIGRATE_CACHE_PATH }}

      - name: Load docker image
        run: docker load -i ${{ env.POSTGRES_CACHE_PATH }}

      - name: run test
        run: |
          make test
